module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'security',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        // apps
        'worklist',
        'reader',
        'patient',
        'insights',
        'connect',
        'console',
        'mobile',
        // services
        'ingestion',
        'ai-worker',
        'ai-dispatcher',
        'ai-aggregator',
        'llm',
        'vision-ai',
        'fhir',
        'dicom',
        'whatsapp',
        'cloud-index',
        'consent',
        'tunnel',
        'edge',
        // packages
        'ui',
        'auth',
        'api-client',
        'event-bus',
        'command-palette',
        'shared-types',
        'dicom-utils',
        // infra
        'infra',
        'ci',
        'docker',
        'db',
        'docs',
        'tests',
        'deps',
        'release',
      ],
    ],
    'subject-case': [0],
    'body-max-line-length': [0],
  },
};
